### ISSUE TITLE
CoupledMCMC unresponsive

### ISSUE THREAD

**Issue by SamPassmore** [nicfel/CoupledMCMC#20]
Hi, 

I am trying to use CoupledMCMC for my mtDNA BEAST analysis - however, this package appears to have issues on my computer and I cannot figure out why. I was hoping you could offer me some advice on what might be wrong. 

I am using an M1 Mac on Ventura 3.3.1 (a), and BEAST 2.7.6

If I try to open a CoupledMCMC Template within BEAUti, I cannot load in any partitions into the program.
If I try to convert an existing xml file to CoupledMCMC by using the Template drop-down, it removes all input editors. 
If I try to convert the file using the "Launch App" command, clicking "Launch" does nothing (but it works for other Apps). 
If I try using the terminal, I am returned this error:
```
Applications/BEAST\ 2.7.6/bin/applauncher MCMC2CoupledMCMC -xml ./CBES_bModeltest.xml -o mc3.xml 
Loading package bModelTest v1.3.3 starbeast3 v1.1.8 SA v2.1.1 BEAST.base v2.7.6 BEASTLabs v2.0.2 BEAST.app v2.7.6 BEAST_CLASSIC v1.6.3 CoupledMCMC v1.2.1 ORC v1.2.0    
About to invoke coupledMCMC.MCMC2CoupledMCMC public static void coupledMCMC.MCMC2CoupledMCMC.main(java.lang.String[]) throws java.lang.Exception
Args:[-xml, ./CBES_bModeltest.xml, -o, mc3.xml]
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beastfx.app.tools.AppLauncher.runAppFromCMD(Unknown Source)
	at beastfx.app.tools.AppLauncher.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at beast.pkgmgmt.launcher.BeastLauncher.run(Unknown Source)
	at beast.pkgmgmt.launcher.AppLauncherLauncher.main(Unknown Source)
Caused by: java.lang.Error: Unresolved compilation problem: 

	at coupledMCMC.MCMC2CoupledMCMC.main(MCMC2CoupledMCMC.java:103)
	... 12 more
```

Can you offer any advice on what might be going wrong?

**Comment by lagerweijgr** [comment]
For me it worked to go back to an earlier version of BEAST (and also an older version of the coupled package). I have the idea that the newest version 1.2.1. does not work properly with the BEAST 2.7.5 or newer. 
I use BEAST 2.7.4 and coupled version 1.2.0.

**Comment by rbouckaert** [comment]
Thanks for those helpful pointers!
There was indeed a problem with the release, which should be fixed now. Can you try and install CoupledMCMC v1.2.2 and see whether the problem persists?

**Comment by lagerweijgr** [comment]
Hi. Thanks for the quick response and release of the new version. For me, the new version made it possible to use the conversion method for converting my .xml file. However after converting the .xml file the analysis will not run in BEAST2 (version 2.7.6). 
I saw a difference in the new .xml file that the number of chains is missing. I added this to the .xml file. Unfortunately it still does not work.

**Comment by rbouckaert** [comment]
Hi Giske, 
Can you make the XML available (e.g. zip up and send to higgs.ml@gmail.com) so I can investigate what is causing the problem?
Cheers, Remco
